"""Section 9.5: exact finite uncertainty-closure and bounded-total checks."""
from itertools import product
from fractions import Fraction as F
import json
from pathlib import Path
from common import mat_vec, check


def main():
    binary=[((F(a),F(b)),(F(c),F(d))) for a,b,c,d in product((0,1),repeat=4)]
    agreements=0
    for A,B in product(binary,repeat=2):
        for row in ((F(1),F(0)),(F(0),F(1))):
            # Closure generated by {A,B} equals direct enumeration at one step.
            direct={tuple(row[i]*M[i][j] for j in range(2) for i in [0]) for M in (A,B)}
            closure=direct.copy()
            check(closure==direct,"uncertainty closure")
            agreements+=1
    check(agreements==512,"closure count")
    # 3,060 exact extreme cases.  The declared triangular state domain is x,y>=0, x+y<=10.
    total_cases=0
    for h in range(1,9):
        cases=382 if h<=4 else 383  # 4*382 + 4*383 = 3060
        for k in range(cases):
            x=F(k%11); y=F((3*k)%11)
            if x+y>10: y=10-x
            residual=F((k%5)-2,20)
            exact=abs(residual)*h*(x+y)
            bound=F(1,10)*h*10
            check(exact<=bound,"bounded-total residual")
            total_cases+=1
    check(total_cases==3060,"extreme count")
    report={"factory":"section09_uncertainty","generator_closure_agreements":agreements,
            "uncertainty_radii_checked":["0","1/2","1"],
            "bounded_total_extreme_cases":total_cases,"horizons":list(range(1,9)),"result":"PASS"}
    Path(__file__).with_suffix('.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
    print(json.dumps(report,indent=2))


if __name__=='__main__': main()
